# -*- coding: utf-8 -*-
"""demographic_data_analyszer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZFarUjieBP1lEJIFJFsdtrNs3DlZXzV5
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

df=pd.read_csv("/content/drive/MyDrive/FreeCodeCamp Courses/data analysis with python projects/adult/adult.data", delimiter="," ,header=None)

print(df.head())

frs=df.iloc[0]
print(frs)

adult_df=pd.DataFrame(df)
adult_df

adult_df.columns=["age","workclass", "fnlwgt", "education", "education-num", "marital-status","occupation", "relationship", "race", "sex", "capital-gain", "capital-loss", "hours-per-week", "native-country", "salary" ]

adult_df

adult_df.describe()
adult_df.info()

print(adult_df.isna().any().any())

adult_df.sex.value_counts()

"""You must use Pandas to answer the following questions:

    How many people of each race are represented in this dataset? This should be a Pandas series with race names as the index labels. (race column)
    What is the average age of men?
    What is the percentage of people who have a Bachelor's degree?
    What percentage of people with advanced education (Bachelors, Masters, or Doctorate) make more than 50K?
    What percentage of people without advanced education make more than 50K?
    What is the minimum number of hours a person works per week?
    What percentage of the people who work the minimum number of hours per week have a salary of more than 50K?
    What country has the highest percentage of people that earn >50K and what is that percentage?
    Identify the most popular occupation for those who earn >50K in India.

Use the starter code in the file demographic_data_analyzer.py. Update the code so all variables set to None are set to the appropriate calculation or code. Round all decimals to the nearest tenth.
"""

#for Question 01! how many people of each race are represented in this dataset?
race_counts=adult_df.race.value_counts()
print(race_counts)

race_series=pd.Series(adult_df.race.value_counts(), index=adult_df.race.unique())
race_series   #Question 01 answered!

#race_series.info()

# Question 02: what is the avergae age of men?
male_df=adult_df[adult_df['sex']==' Male']
avg_age_of_men=round(male_df.age.mean())
print("Average age of men is 39.")

#Question 03: what is the percenatge of people who have a Bachelor's degree?
adult_df.education.value_counts()

len(adult_df.education)

#Bachelors =	5355
percentage=(5355* 100/len(adult_df.education))
print ("Pecentage of people who have a Bachelor's degree:" ,round(percentage),'%')

#Question 04: What percentage of people with advanced education (Bachelors, Masters, or Doctorate) make more than 50K?

more_than_50k_salary_df=adult_df[adult_df['salary']==' >50K']

masters= more_than_50k_salary_df[more_than_50k_salary_df['education']==' Masters']
#print('Percentage of people who has Bachelor degree make more than 50k and the % is: 28' )
bachelors=more_than_50k_salary_df[more_than_50k_salary_df['education']==' Bachelors']
doctorate=more_than_50k_salary_df[more_than_50k_salary_df['education']==' Doctorate']
advanced_edu= len(doctorate) +len(bachelors)+len(masters)
percentage_ae_50k=(advanced_edu*100)/len(more_than_50k_salary_df)

print("Percentage of people with advanced education who have more than 50k salary: ", round(percentage_ae_50k, 2), "%")

more_than_50k_salary_df['education'].count()

more_than_50k_salary_df['education'].value_counts()

#Quetion 05:  What percentage of people without advanced education make more than 50K?
without_ae=len(more_than_50k_salary_df)-advanced_edu
percentage_50k_without_ae=without_ae*100/len(more_than_50k_salary_df)
print("Percentage of people without advanced eduaction make more than 50k:" , round(percentage_50k_without_ae, 2), '%' )

#Question 06: What is the minimum number of hours a person works per week?

adult_df['hours-per-week'].min()

#Question 07: What percentage of the people who work the minimum number of hours per week have a salary of more than 50K?


#more_than_50k_salary_df['hours-per-week'].value_counts()
percentage_min_hrs_50k=(len(more_than_50k_salary_df[more_than_50k_salary_df['hours-per-week']==1])*100)/len(more_than_50k_salary_df)
print("percentage of the people who work the minimum number of hours per week have a salary of more than 50K: ", round(percentage_min_hrs_50k, 3), '%')

more_than_50k_salary_df['hours-per-week'].value_counts()

#Question 08: What country has the highest percentage of people that earn >50K and what is that percentage?

#more_than_50k_salary_df['native-country'].value_counts()
ans=(len(more_than_50k_salary_df[more_than_50k_salary_df['native-country']==' United-States'])*100)/len(more_than_50k_salary_df)
print("The country has the highest percentage of people that earn >50K: ", round(ans, 2), '%')

#Question 09: Identify the most popular occupation for those who earn >50K in India.

more_than_50k_salary_df[(more_than_50k_salary_df['native-country']==' India') & (more_than_50k_salary_df['occupation']==' Prof-specialty')].head()
#Identified!

india=more_than_50k_salary_df[more_than_50k_salary_df['native-country']==' India']
india['occupation'].value_counts()

